import type { IAppliance } from "@/types";

export const FALLBACK_APPLIANCES: IAppliance[] = [
  { id:"a1",name:"LED Bulb",defaultWattage:10,category:"Lighting",icon:"💡" },
  { id:"a2",name:"CFL Bulb",defaultWattage:23,category:"Lighting",icon:"💡" },
  { id:"a3",name:"Fluorescent Tube",defaultWattage:40,category:"Lighting",icon:"💡" },
  { id:"a4",name:"Ceiling Fan",defaultWattage:75,category:"Cooling",icon:"🌀" },
  { id:"a5",name:"Standing Fan",defaultWattage:55,category:"Cooling",icon:"🌀" },
  { id:"a6",name:"Air Conditioner (1HP)",defaultWattage:1000,category:"Cooling",icon:"❄️" },
  { id:"a7",name:"Air Conditioner (1.5HP)",defaultWattage:1500,category:"Cooling",icon:"❄️" },
  { id:"a8",name:"Air Conditioner (2HP)",defaultWattage:2000,category:"Cooling",icon:"❄️" },
  { id:"a9",name:"Refrigerator (Small)",defaultWattage:100,category:"Kitchen",icon:"🧊" },
  { id:"a10",name:"Refrigerator (Large)",defaultWattage:200,category:"Kitchen",icon:"🧊" },
  { id:"a11",name:"Deep Freezer",defaultWattage:250,category:"Kitchen",icon:"🧊" },
  { id:"a12",name:"Microwave Oven",defaultWattage:1200,category:"Kitchen",icon:"🍳" },
  { id:"a13",name:"Electric Kettle",defaultWattage:1500,category:"Kitchen",icon:"☕" },
  { id:"a14",name:"Blender",defaultWattage:350,category:"Kitchen",icon:"🫙" },
  { id:"a15",name:"Rice Cooker",defaultWattage:700,category:"Kitchen",icon:"🍚" },
  { id:"a16",name:"Toaster",defaultWattage:800,category:"Kitchen",icon:"🍞" },
  { id:"a17",name:"Electric Oven",defaultWattage:2400,category:"Kitchen",icon:"🔥" },
  { id:"a18",name:"Dishwasher",defaultWattage:1800,category:"Kitchen",icon:"🍽️" },
  { id:"a19",name:"Television (LED 32\")",defaultWattage:50,category:"Entertainment",icon:"📺" },
  { id:"a20",name:"Television (LED 55\")",defaultWattage:100,category:"Entertainment",icon:"📺" },
  { id:"a21",name:"Sound System",defaultWattage:150,category:"Entertainment",icon:"🔊" },
  { id:"a22",name:"Projector",defaultWattage:300,category:"Entertainment",icon:"🎬" },
  { id:"a23",name:"Desktop Computer",defaultWattage:200,category:"Office",icon:"🖥️" },
  { id:"a24",name:"Laptop",defaultWattage:65,category:"Office",icon:"💻" },
  { id:"a25",name:"Printer",defaultWattage:50,category:"Office",icon:"🖨️" },
  { id:"a26",name:"Router/Modem",defaultWattage:15,category:"Office",icon:"📡" },
  { id:"a27",name:"Phone Charger",defaultWattage:10,category:"Office",icon:"🔌" },
  { id:"a28",name:"Washing Machine",defaultWattage:500,category:"Laundry",icon:"🫧" },
  { id:"a29",name:"Electric Iron",defaultWattage:1000,category:"Laundry",icon:"👔" },
  { id:"a30",name:"Water Pump",defaultWattage:750,category:"Utility",icon:"💧" },
  { id:"a31",name:"Water Heater",defaultWattage:2000,category:"Utility",icon:"🚿" },
  { id:"a32",name:"Air Purifier",defaultWattage:60,category:"Utility",icon:"🌬️" },
  { id:"a33",name:"Sewing Machine",defaultWattage:100,category:"Utility",icon:"🧵" },
  { id:"a34",name:"Security Light",defaultWattage:30,category:"Security",icon:"🔦" },
  { id:"a35",name:"CCTV System",defaultWattage:60,category:"Security",icon:"📷" },
  { id:"a36",name:"Hair Dryer",defaultWattage:1500,category:"Personal",icon:"💇" },
  { id:"a37",name:"POS Terminal",defaultWattage:50,category:"Business",icon:"💳" },
  { id:"a38",name:"Barbing Clipper",defaultWattage:15,category:"Business",icon:"✂️" },
  { id:"a39",name:"Grinding Machine",defaultWattage:1800,category:"Business",icon:"⚙️" },
  { id:"a40",name:"Chest Cooler/Display",defaultWattage:350,category:"Business",icon:"🧃" },
];

export const APPLIANCE_CATEGORIES_LIST = [...new Set(FALLBACK_APPLIANCES.map(a => a.category))];
